# Generated by Django 5.1.5 on 2025-02-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryDishesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("uklon", "Uklon"), ("uber", "Uber")], max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not started", "Not started"),
                            ("ongoing", "Ongoing (in delivery)"),
                            ("cancelled user", "Cancelled by User (customer)"),
                            ("cancelled system", "Cancelled by System"),
                            ("cancelled driver", "Cancelled by Driver (or provider)"),
                            ("done", "Successfully finished"),
                            ("failed", "Successfully finished"),
                            ("stolen", "Stolen by driver"),
                        ],
                        max_length=50,
                    ),
                ),
                ("addresses", models.TextField()),
                ("external_order_id", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "dishes_orders_deliveries",
            },
        ),
    ]
