# Generated by Django 5.1.5 on 2025-02-06 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDishesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("addresses", models.TextField()),
                ("external_order_id", models.CharField(max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food.dishesorder",
                    ),
                ),
            ],
            options={
                "db_table": "dishes_orders_deliveries",
            },
        ),
    ]
