services:
  api:
    build: .
    container_name: catering_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    depends_on:
      - database

  database:
    image: "postgres:17"
    container_name: catering_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catering
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
