services:
  api: &api
    build: .
    # for dubugging in Docker Container
    stdin_open: true
    tty: true
    container_name: catering_api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    depends_on:
      - database

  worker:
    <<: *api
    container_name: catering_worker
    ports: []
    entrypoint: bash
    command: -c "watchmedo auto-restart --pattern='*.py' -- celery -A config worker -l DEBUG"
    env_file: .env

  database:
    image: "postgres:17"
    container_name: catering_database
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  cache:
    image: "redis:latest"
    container_name: catering_cache
    ports:
      - "6379:6379"

  broker:
    image: "redis:latest"
    container_name: catering_broker
    ports:
      - "6380:6379"

  mailing:
    image: axllent/mailpit
    container_name: catering_mailing
    ports:
      - "8025:8025" # HTTP
      - "1025:1025" # SMTP
    environment:
      MP_MAX_MESSAGES: 100
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  mock_melange:
    build:
      context: .
      dockerfile: Dockerfile.tests
      target: melange
    container_name: catering_mock_melange
    ports:
      - "8001:8000"

  mock_bueno:
    build:
      context: .
      dockerfile: Dockerfile.tests
      target: bueno
    container_name: catering_mock_bueno
    ports:
      - "8002:8000"

  mock_uklon:
    build:
      context: .
      dockerfile: Dockerfile.tests
      target: uklon
    container_name: catering_mock_uklon
    ports:
      - "8003:8000"

volumes:
  pg_data: {}
