services:
  api:
    build: .
    # for dubugging in Docker Container
    # stdin_open: true
    # tty: true
    container_name: catering_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    depends_on:
      - database

  database:
    image: "postgres:17"
    container_name: catering_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catering
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mailing:
    image: axllent/mailpit
    container_name: catering_mailing
    ports:
      - "8025:8025" # HTTP
      - "1025:1025" # SMTP
    environment:
      MP_MAX_MESSAGES: 100
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  pg_data: {}
