FROM python:3.12-slim

# ENV PYTHONUNBUFFERED=1

RUN apt-get update -y \
    # dependencies for building Python packages && cleaning apt apt packages
    && apt-get install -y build-essential \
    && rm -rf /var/lib/apt/lists/*


RUN pip install --upgrade pip setuptools requests httpx uvicorn fastapi pydantic

WORKDIR /app/
COPY ./test/providers ./

CMD ["uvicorn", "manage.py", "runserver", "0.0.0.0:8000"]

