services:
  broker:
    image: "redis:latest"
    container_name: catering_broker
    ports:
      - "6380:6379"

  cache:
    image: "redis:latest"
    container_name: catering_cache
    ports:
      - "6379:6379"

  mailing:
    image: "axllent/mailpit:latest"
    container_name: catering_mailing
    environment:
      MP_MAX_MESSAGES: 100
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - "8025:8025"

  database:
    image: postgres:17
    container_name: catering_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catering
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

      # paste ``&app`` after Celery is added
    api: &api
    build: .
    image: catering_api
    container_name: catering_api
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - .:/app/

    worker:
      <<: *api
    container_name: catering_worker
    ports: []
    entrypoint: bash
    command: -c "watchmedo auto-restart --pattern='*.py' --recursive -- celery -A config worker -l DEBUG"

    volumes:
      pg_data: {}
