"""
=================================================================
BUENO
=================================================================
STATUSES: not started, cooking, cooked, finished
HTTP POST /
    order: [
        {
            dish: string
            quantity: number
        }, ...
    ]

RESPONSE
    id: string,  // generated by restaurant
    status: string


WEBHOOK HTTP POST /webhooks/bueno
    id: string,
    status: string

=================================================================
MELANGE
=================================================================

STATUS: not started, cooking, cooked, finished
HTTP POST /api/orders
    order: [
        {
            dish: string
            quantity: number
        }, ...
    ]

RESPONSE
    id: string,
    status: string

HTTP GET /api/orders/<ID>
    status: string


=================================================================

ORDER IN CACHE representation
{
    INTERNAL_ORDER_ID: {
        melange: {
            external_id: string,
            status: string,
            dishes: [
                {
                    dish: string,
                    quantity: number,
                }, ...
            ]
        },
        bueno: {
            external_id: string,
            status: string,
            dishes: [
                {
                    dish: string,
                    quantity: number,
                }, ...
            ]
        }
    }
}
"""
