# Generated by Django 5.1.5 on 2025-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="provider",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
