# Generated by Django 5.1.5 on 2025-03-24 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_order_eta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="food.order",
            ),
        ),
    ]
