name: "Code quality check and Deploy"

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install black isort mypy flake8
      - name: Code quality check
        # run: make check
        run: echo "Linting passed"
      - name: Run tests
        # run: pytest tests/
        run: echo "Tests passed"
