name: "Code quality check and Deploy"

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install black isort mypy flake8 pytest pytest-django
      - name: Code quality check
        # run: make check
        run: echo "Linting passed"
      - name: Run tests
        run: pytest tests/

  deployment:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - uses: actions/checkout@v4
      - name: executing remote ssh commands using SSH PRIVATE KEY
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            cd ~/hillel_catering_api
            git pull origin main
            docker compose build
            docker compose down
            docker compose up -d api
            docker compose exec api python manage.py migrate
            echo "🚀 Deployment is done"
